apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blitzy-celery
  description: Distributed Task Queue (development branch)
  tags:
  - distributed-systems
  - python
  annotations:
    github.com/project-slug: Blitzy-Sandbox/blitzy-celery
    backstage.io/source-location: url:https://github.com/Blitzy-Sandbox/blitzy-celery/tree/main/
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: blitzy-sandbox
  system: blitzy-sandbox-projects
